'use client';

import { Printer, X } from 'lucide-react';
import { useState, useRef } from 'react';
import { Shortcut, OSType, Language, isLocalizedKeys } from '@/types';
import { cn } from '@/lib/utils';

interface PrintModalProps {
  isOpen: boolean;
  onClose: () => void;
  shortcuts: Shortcut[];
  os: OSType;
  language: Language;
  appName: string;
}

export function PrintModal({ isOpen, onClose, shortcuts, os, language, appName }: PrintModalProps) {
  const printRef = useRef<HTMLDivElement>(null);
  const [isPrinting, setIsPrinting] = useState(false);

  const handlePrint = () => {
    setIsPrinting(true);
    setTimeout(() => {
      window.print();
      setIsPrinting(false);
    }, 100);
  };

  if (!isOpen) return null;

  // Group shortcuts by category
  const groupedShortcuts = shortcuts.reduce((acc, shortcut) => {
    const category = shortcut.category;
    if (!acc[category]) {
      acc[category] = [];
    }
    acc[category].push(shortcut);
    return acc;
  }, {} as Record<string, Shortcut[]>);

  return (
    <>
      {/* Modal Overlay */}
      <div
        onClick={onClose}
        className="fixed inset-0 bg-black/90 z-50 print-hide"
      />

      {/* Modal Content */}
      <div className="print-modal-container fixed inset-4 md:inset-10 bg-[#0a0a0a] rounded-2xl border border-white/10 z-50 overflow-hidden flex flex-col print:static print:inset-auto print:bg-white print:border-none print:rounded-none print:overflow-visible">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-white/10 print-hide">
          <h2 className="text-xl font-semibold text-white">{appName} Shortcuts</h2>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              disabled={isPrinting}
              className="flex items-center gap-2 px-4 py-2 rounded-lg bg-blue-500 hover:bg-blue-600 text-white font-medium transition-all duration-150 hover:scale-105 active:scale-95 disabled:opacity-50"
            >
              <Printer className="w-4 h-4" />
              <span>{isPrinting ? 'Printing...' : 'Print'}</span>
            </button>
            <button
              onClick={onClose}
              className="p-2 rounded-lg text-zinc-400 hover:text-white hover:bg-white/10 transition-all duration-150 hover:scale-105 active:scale-95"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Content */}
        <div 
          ref={printRef}
          className="print-content flex-1 overflow-auto p-6 print:p-4 print:overflow-visible print:bg-white"
        >
          {/* Print Header */}
          <div className="hidden print:block mb-6">
            <h1 className="text-2xl font-bold text-black">{appName} Keyboard Shortcuts</h1>
            <p className="text-gray-600 text-sm mt-1">
              {os === 'win' ? 'Windows' : 'macOS'} • Generated by KeyMaster
            </p>
          </div>

          {/* Categories */}
          <div className="space-y-8 print:space-y-4">
            {Object.entries(groupedShortcuts).map(([category, categoryShortcuts]) => (
              <div key={category} className="print:break-inside-avoid">
                <h3 className="text-lg font-semibold text-white mb-4 print:text-black print:text-base print:mb-2">
                  {category}
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-2 print:grid-cols-2 print:gap-1">
                  {categoryShortcuts.map((shortcut) => {
                    const keys = isLocalizedKeys(shortcut.keys)
                      ? shortcut.keys[language][os]
                      : shortcut.keys[os];
                    const action = shortcut.action[language];

                    return (
                      <div
                        key={shortcut.id}
                        className="flex items-center justify-between p-3 rounded-lg bg-white/5 print:bg-gray-100 print:p-2 print:rounded"
                      >
                        <span className="text-sm text-zinc-300 print:text-black">
                          {action}
                        </span>
                        <div className="flex items-center gap-1">
                          {keys.map((key, i) => (
                            <kbd
                              key={i}
                              className="px-2 py-1 text-xs font-mono rounded bg-zinc-800 text-white border border-zinc-700 print:bg-gray-200 print:text-black print:border-gray-300"
                            >
                              {key}
                            </kbd>
                          ))}
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>

          {/* Print Footer */}
          <div className="hidden print:block mt-8 pt-4 border-t border-gray-200 text-center text-gray-500 text-xs">
            Generated by KeyMaster • {new Date().toLocaleDateString()}
          </div>
        </div>
      </div>

      {/* Print Styles */}
      <style jsx global>{`
        @media print {
          /* Hide everything first */
          body > *:not(.print-modal-container) {
            display: none !important;
          }
          
          /* Reset body */
          body {
            background: white !important;
            color: black !important;
          }
          
          /* Show only print content */
          .print-modal-container {
            position: static !important;
            display: block !important;
            visibility: visible !important;
          }
          
          .print-content {
            display: block !important;
            visibility: visible !important;
            background: white !important;
            color: black !important;
          }
          
          .print-content * {
            visibility: visible !important;
          }
          
          .print-hide {
            display: none !important;
          }

          @page {
            margin: 1cm;
            size: A4;
          }
        }
      `}</style>
    </>
  );
}
