'use client';

import { Printer, X } from 'lucide-react';
import { useState } from 'react';
import { Shortcut, OSType, Language, isLocalizedKeys } from '@/types';

interface PrintModalProps {
  isOpen: boolean;
  onClose: () => void;
  shortcuts: Shortcut[];
  os: OSType;
  language: Language;
  appName: string;
}

export function PrintModal({ isOpen, onClose, shortcuts, os, language, appName }: PrintModalProps) {
  const [isPrinting, setIsPrinting] = useState(false);

  // Group shortcuts by category
  const groupedShortcuts = shortcuts.reduce((acc, shortcut) => {
    const category = shortcut.category;
    if (!acc[category]) {
      acc[category] = [];
    }
    acc[category].push(shortcut);
    return acc;
  }, {} as Record<string, Shortcut[]>);

  const handlePrint = () => {
    setIsPrinting(true);
    
    // Generate HTML content for printing
    let shortcutsHTML = '';
    
    Object.entries(groupedShortcuts).forEach(([category, categoryShortcuts]) => {
      shortcutsHTML += `
        <div style="margin-bottom: 24px; break-inside: avoid;">
          <h3 style="font-size: 16px; font-weight: 600; margin-bottom: 12px; color: #1a1a1a; border-bottom: 2px solid #3b82f6; padding-bottom: 4px;">${category}</h3>
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 8px;">
            ${categoryShortcuts.map(shortcut => {
              const keys = isLocalizedKeys(shortcut.keys)
                ? shortcut.keys[language][os]
                : shortcut.keys[os];
              const action = shortcut.action[language];
              
              return `
                <div style="display: flex; justify-content: space-between; align-items: center; padding: 8px 12px; background: #f5f5f5; border-radius: 6px; gap: 8px;">
                  <span style="font-size: 13px; color: #333;">${action}</span>
                  <div style="display: flex; gap: 4px; flex-shrink: 0;">
                    ${keys.map(key => `<kbd style="padding: 4px 8px; font-size: 11px; font-family: monospace; background: #e5e5e5; border: 1px solid #ccc; border-radius: 4px; white-space: nowrap;">${key}</kbd>`).join('')}
                  </div>
                </div>
              `;
            }).join('')}
          </div>
        </div>
      `;
    });

    const printContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>${appName} Keyboard Shortcuts - KeyMaster</title>
          <style>
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 24px; color: #1a1a1a; }
            @media print {
              body { padding: 0; }
              @page { margin: 1cm; size: A4; }
            }
          </style>
        </head>
        <body>
          <div style="margin-bottom: 24px; padding-bottom: 16px; border-bottom: 2px solid #1a1a1a;">
            <h1 style="font-size: 24px; font-weight: 700; margin-bottom: 4px;">${appName} Keyboard Shortcuts</h1>
            <p style="font-size: 14px; color: #666;">${os === 'win' ? 'Windows' : 'macOS'} • Generated by KeyMaster • ${new Date().toLocaleDateString()}</p>
          </div>
          ${shortcutsHTML}
          <div style="margin-top: 32px; padding-top: 16px; border-top: 1px solid #ddd; text-align: center; color: #999; font-size: 12px;">
            KeyMaster - The Ultimate Keyboard Shortcuts Reference
          </div>
        </body>
      </html>
    `;

    // Open new window and print
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(printContent);
      printWindow.document.close();
      
      // Wait for content to load then print
      printWindow.onload = () => {
        printWindow.print();
        printWindow.close();
      };
      
      // Fallback for browsers that don't fire onload
      setTimeout(() => {
        if (!printWindow.closed) {
          printWindow.print();
        }
        setIsPrinting(false);
      }, 500);
    } else {
      setIsPrinting(false);
      alert('Please allow popups to print');
    }
  };

  if (!isOpen) return null;

  return (
    <>
      {/* Modal Overlay */}
      <div
        onClick={onClose}
        className="fixed inset-0 bg-black/90 z-50"
      />

      {/* Modal Content */}
      <div className="fixed inset-4 md:inset-10 bg-[#0a0a0a] rounded-2xl border border-white/10 z-50 overflow-hidden flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-white/10">
          <h2 className="text-xl font-semibold text-white">{appName} Shortcuts</h2>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              disabled={isPrinting}
              className="flex items-center gap-2 px-4 py-2 rounded-lg bg-blue-500 hover:bg-blue-600 text-white font-medium transition-all disabled:opacity-50"
            >
              <Printer className="w-4 h-4" />
              <span>{isPrinting ? 'Printing...' : 'Print'}</span>
            </button>
            <button
              onClick={onClose}
              className="p-2 rounded-lg text-zinc-400 hover:text-white hover:bg-white/10 transition-all"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Preview Content */}
        <div className="flex-1 overflow-auto p-6">
          {/* Header Preview */}
          <div className="mb-6 pb-4 border-b border-white/20">
            <h1 className="text-2xl font-bold text-white">{appName} Keyboard Shortcuts</h1>
            <p className="text-zinc-400 text-sm mt-1">
              {os === 'win' ? 'Windows' : 'macOS'} • Generated by KeyMaster
            </p>
          </div>

          {/* Categories Preview */}
          <div className="space-y-6">
            {Object.entries(groupedShortcuts).map(([category, categoryShortcuts]) => (
              <div key={category}>
                <h3 className="text-lg font-semibold text-white mb-3 pb-1 border-b border-blue-500/50">
                  {category}
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                  {categoryShortcuts.map((shortcut) => {
                    const keys = isLocalizedKeys(shortcut.keys)
                      ? shortcut.keys[language][os]
                      : shortcut.keys[os];
                    const action = shortcut.action[language];

                    return (
                      <div
                        key={shortcut.id}
                        className="flex items-center justify-between p-3 rounded-lg bg-white/5"
                      >
                        <span className="text-sm text-zinc-300">{action}</span>
                        <div className="flex items-center gap-1">
                          {keys.map((key, i) => (
                            <kbd
                              key={i}
                              className="px-2 py-1 text-xs font-mono rounded bg-zinc-800 text-white border border-zinc-700"
                            >
                              {key}
                            </kbd>
                          ))}
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>

          {/* Footer Preview */}
          <div className="mt-8 pt-4 border-t border-white/10 text-center text-zinc-500 text-xs">
            KeyMaster - The Ultimate Keyboard Shortcuts Reference
          </div>
        </div>
      </div>
    </>
  );
}
